# Generated by Django 5.2.7 on 2025-10-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=100)),
                ('email_user', models.EmailField(max_length=150, unique=True)),
                ('password_user', models.CharField(max_length=150)),
            ],
        ),
    ]
